sonar.projectName=DevSecOps Security Pipeline
sonar.sourceEncoding=UTF-8

sonar.sources=app.py
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=.venv/**,reports/**
sonar.python.version=3.13
